const nav=document.getElementById('nav'),view=document.getElementById('view'),clock=document.getElementById('clock'),toast=document.getElementById('toast');
const data={overview:{title:'Overview',cards:[['🟢','12','Online Now'],['👥','1,284','Users'],['🎬','342','Videos'],['👁','18,492','Views'],['❤️','6,731','Likes'],['💰','$4,820','Payments'],['💸','$1,260','Payouts'],['🔐','SECURE','Security']]},users:{title:'Users',rows:['🟢 user_1284 — Online now','🟢 user_1198 — Online 2m','⚪ user_1190 — Left 3m','🟢 user_1104 — Online 4m']},videos:{title:'Videos',rows:['video_0342 — Uploaded 1m','video_0318 — Published 4m','video_0309 — Processing 7m','video_0298 — Published 12m']},views:{title:'Views',rows:['18,492 total views','1,284 active users','92 qualified views today','4,820 watch sessions']},likes:{title:'Likes',rows:['6,731 total likes','+48 today','video_0318 — +12','video_0298 — +8']},payments:{title:'Payments',rows:['$4,820 completed','$520 pending','$140 failed','Provider status: monitored']},payouts:{title:'Payouts',rows:['$1,260 paid','2 requests under review','$340 processing','No failed payouts']},security:{title:'Security',rows:['Owner session — SECURE','Passkey — READY','Failed logins — 0','Alerts — 1 informational']},audit:{title:'Audit Log',rows:['23:44 OWNER_LOGIN','23:43 USER_LOGIN user_1284','23:42 VIDEO_UPLOADED video_0342','23:41 VIEW_COUNTED video_0318']},alerts:{title:'Alerts',rows:['INFO — New user session','INFO — Video upload received','OK — No critical security alerts','OK — No service outage']},health:{title:'System Health',rows:['Frontend — ONLINE','Database — READY (local test)','Event pipeline — READY','Integration — DISCONNECTED (planned)']}};
const keys=Object.keys(data);
function showToast(t){toast.textContent=t;toast.style.display='block';setTimeout(()=>toast.style.display='none',1800)}
function renderNav(active){nav.innerHTML=keys.map(k=>'<button class="'+(k===active?'active':'')+'" data-k="'+k+'">'+data[k].title+'</button>').join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>render(b.dataset.k))}
function render(k='overview'){renderNav(k);const d=data[k];if(k==='overview'){view.innerHTML='<div class="section-title"><h2>'+d.title+'</h2><small>All systems monitored</small></div><div class="stats">'+d.cards.map(x=>'<article class="card"><span>'+x[0]+'</span><strong>'+x[1]+'</strong><small>'+x[2]+'</small></article>').join('')+'</div><section class="panel"><div class="section-title"><h2>⚡ Live Activity</h2><small>4 events</small></div>'+['🟢 User entered — user_1284','🎬 Video uploaded — video_0342','❤️ Like received — video_0318','🚪 User left — user_1190'].map(x=>'<div class="row"><span>'+x+'</span><span class="ok">LIVE</span></div>').join('')+'</section><div class="grid">'+keys.slice(1).map(k=>'<button class="action" data-k="'+k+'"><b>'+data[k].title+'</b><small>Open module</small></button>').join('')+'</div><button id="stop" class="danger">STOP ALL</button>';view.querySelectorAll('.action').forEach(b=>b.onclick=()=>render(b.dataset.k));document.getElementById('stop').onclick=()=>{if(confirm('STOP ALL actions?'))showToast('STOP ALL recorded — control backend comes later')}}else{view.innerHTML='<div class="section-title"><h2>'+d.title+'</h2><small>Independent test data</small></div><section class="panel">'+d.rows.map(x=>'<div class="row"><span>'+x+'</span><span class="ok">●</span></div>').join('')+'</section>'}}
function tick(){clock.textContent=new Date().toLocaleTimeString([], {hour12:false})}tick();setInterval(tick,1000);
document.getElementById('lockBtn').onclick=()=>showToast('Owner control locked');
render();
